return {
    {
        Name = "Infantry",
        {
            Name = "Line",
            Price = 80,
        },
        {
            Name = "Elite",
            Price = 200
        },
        {
            Name = "Skirmish",
            Price = 150
        }
    },

    {
        Name = "Cavalry",
        {
            Name = "Cuirassier",
            Price = 125
        },
        {
            Name = "Lancer",
            Price = 150
        },
        {
            Name = "Hussar",
            Price = 75
        },
        {
            Name = "Dragoon",
            Price = 200
        },
    },
    
    {
        Name = "Artillery",
        {
            Name = "Cannon",
            Price = 100
        },
        {
            Name = "Rocket",
            Price = 125
        }
    }
}